name: CICD-SSH
on:
  push:
      branches: [ main ]
    #   paths:
    #     - 'part2/04-cicd/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }} 
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 2232
        script: |
            cd ~/final-project
            source /opt/ml/.local/share/virtualenvs/final-project-1ugMOtgr/bin/activate
            # pipenv shell
            cd ~/final-project/testbed/FastAPI_test/
            # nohup uvicorn app_single:app --reload --host=0.0.0.0 --port=30001 &
            # nohup uvicorn app_single:app --reload --host=0.0.0.0 --port=30001 < /dev/null & > /dev/null &
            sleep 4
            # echo -ne '\n'
            # cd ~/testbed/FastAPI_test
            # nohup uvicorn app_single:app --reload --host=0.0.0.0 --port=30001 &
            # sleep 5
            # kill -9 $(lsof -t -i:30001)
            # cd ~
            # mkdir kiki
            # cd ${{ github.event.repository.name }}/part2/04-cicd
            # sh deploy_ssh.sh