name: CICD-SSH
on:
  [pull_request]
  # push:
  #     branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 2232
        script: |
            cd ~/github-action-test
            git pull
            cd ~/final-project

            source /opt/ml/.local/share/virtualenvs/final-project-1ugMOtgr/bin/activate
            cd ~/final-project/testbed/FastAPI_test/
            if [ -n "$(lsof -t -i:30001)" ]; then
              echo "kill FastAPI"
              kill -9 $(lsof -t -i:30001)
            fi
            sleep 5
            nohup uvicorn app_single:app --reload --host=0.0.0.0 --port=30001 > nohup.out 2> nohup.err < /dev/null &